/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jyamlj;

import java.util.ArrayList;

import jyamlj.JsonLexer.TokenPair;

public class App {

	public static void main(String[] args) throws JsonLexer.InvalidLexerException, InvalidParserException {
		String someJson = "{\"scotch\":\"bruh\", \"thomp\":[1,2, 3, \"moment\", {\"a\": 1.1}]    }";
		System.out.println("input: " + someJson);
		JsonLexer l = new JsonLexer(someJson);
		ArrayList<TokenPair> tpl = l.lex();
		ParsedObject o = new ParsedObject().parse(tpl);
		System.out.println("parsed: " + o);
	}
}
